XIVY-12538 program 'userconfig' as map
axonivy/inscription-client pull request #352
Opened 2023-11-06 15:07 UTC by ivy-rew

2023-11-06 15:23 UTC, ivy-lli approved these changes

2023-11-07 08:57 UTC, ivy-lli requested changes

2023-11-07 08:57 UTC, ivy-lli commented on packages/editor/src/components/parts/program/configuration/ConfigurationPart.tsx
> +        <div key={index}>{renderWidgetComponent(widget, index.toString())}</div>
not sure that this is correct. 
As far as I understood this, you should now have a id on the widget, which is corresponding to the key of the config data structure

2023-11-07 08:57 UTC, ivy-lli commented on packages/protocol/src/defaults/common-defaults.ts
> +  userConfig: { '1': '' }
i think the default of this is an empty object...

2023-11-07 09:32 UTC, ivy-rew commented on packages/editor/src/components/parts/program/configuration/ConfigurationPart.test.tsx
> +      userConfig: { directory: '123' }
directory : /tmp/myDir

2023-11-07 09:38 UTC, ivy-lli commented on packages/protocol/src/defaults/common-defaults.ts
> +  userConfig: { '': '' }
why not {}?

2023-11-07 10:17 UTC, ivy-lli approved these changes

2023-11-07 10:38 UTC, merged