XIVY-12797 Impl. of expandable Code Editor
axonivy/inscription-client pull request #469
Opened 2024-01-04 11:46 UTC by ivy-edp

I have now created the expandable code editor. I have already integrated it into the StartPart and TaskPart. However, before incorporating it into all other locations (approximately 7 additional places where the ScriptArea is used), I would like to hear your opinion on whether the integration in these two parts is okay. Even though we discussed earlier that I should leave the ScriptArea component as it is and not add additional parameters and if/else statements, it might now make sense to incorporate it directly there. This way, I could avoid code repetition in too many places. Additionally, I believe that the ScriptArea is only used in CodeParts, so the MaximizedCodeEditorBrowser always needs to be integrated with a ScriptArea. However, I might be mistaken, and it could be better to incorporate everything as shown in the StartPart and TaskPart, keeping the ScriptArea doing only what it was originally intended for. What do you think?

![grafik](https://github.com/axonivy/inscription-client/assets/141223521/c89db90d-2af2-445e-95b2-b15eff78137d)
![grafik](https://github.com/axonivy/inscription-client/assets/141223521/9a70fd42-4ccd-437a-ba11-392523b74360)

2024-01-04 13:25 UTC, ivy-lli requested changes

2024-01-04 13:25 UTC, ivy-lli commented on packages/editor/src/components/browser/MaximizedCodeEditorBrowser.tsx
> +  }, []);
pretty sure this is not needed

2024-01-04 13:25 UTC, ivy-lli commented on packages/editor/src/components/browser/MaximizedCodeEditorBrowser.tsx
> +        </div>
make own component

2024-01-04 13:25 UTC, ivy-lli commented on packages/editor/src/components/browser/useMaximizedCodeEditor.ts
> +  return { isMaximizedCodeEditorOpen, maximizeCode, setIsMaximizedCodeEditorOpen };
```
return { openState: {isMaximizedCodeEditorOpen, setIsMaximizedCodeEditorOpen}, maximizeCode };
```

2024-01-04 15:27 UTC, ivy-lli requested changes

2024-01-04 15:27 UTC, ivy-lli commented on packages/editor/src/components/browser/MaximizedCodeEditorBrowser.tsx
> +    </>
fragment not needed

2024-01-04 15:27 UTC, ivy-lli commented on packages/editor/src/components/widgets/code-editor/ScriptArea.tsx
> +  openState: {
maybe maximizeState or something like that is a bit clearer for a user of the ScriptArea...

2024-01-04 15:27 UTC, ivy-lli commented on packages/editor/src/components/widgets/headlineControls/HeadlineControls.tsx
> +  open?: boolean;
the open has nothing to do with this component IMO. This is only a special case for the collapsible, that if it is open the controls are shown. So just handle it there.

2024-01-04 15:27 UTC, ivy-lli commented on packages/editor/src/monaco/monaco-editor-util.ts
> +  contextmenu: false, // Disabling context menu
already in the default MONACO_OPTIONS

2024-01-04 15:27 UTC, ivy-lli commented on packages/editor/src/monaco/monaco-editor-util.ts
> +  cursorBlinking: 'blink',
isn't this the default?

2024-01-04 15:27 UTC, ivy-lli commented on packages/editor/src/components/widgets/collapsible/Collapsible.tsx
> +      <div className={`collapsible-header${!open ? '-closed' : ''}`}>
I wouldn't change the whole class. Makes it only much harder to test IMO.
Better don't change the default component class, and handle such state stuff in a second class or in a data attribute e.g. `data-state={open ? 'open' : 'closed'}`

And if you do such things, I can only speak for myself, but IMO negative stuff is much harder to read. So even if you don't change this to the attribute style I would write it like `open ? '' : '-closed'`

2024-01-04 15:28 UTC, ivy-lli commented
a lot better IMO. Some small stuff to improve :)

2024-01-05 07:25 UTC, ivy-edp commented on packages/editor/src/monaco/monaco-editor-util.ts
> +  cursorBlinking: 'blink',
yes, you're right 👍

2024-01-05 07:40 UTC, ivy-lli approved these changes

2024-01-05 07:40 UTC, ivy-lli commented on packages/editor/src/components/widgets/collapsible/Collapsible.css
> +.collapsible-root .collapsible-header:has([data-state='open']) {
`:has` is not needed here
just do `.collapse-header[data-state='open']`

And I think you should have a default style without a data-state and then the style for a specific data state e.g. 
```css
.collapsible-root .collapsible-header {
  display: flex;
}
.collapsible-root .collapsible-header[data-state='open'] {
  justify-content: space-between;
  align-items: center;
}
```

2024-01-05 07:40 UTC, ivy-lli commented on packages/editor/src/components/widgets/collapsible/Collapsible.css
> +.collapsible-root .collapsible-header:has([data-state='open']) {
Ah if you want to check the child state, yes then has is needed.
```css
.collapsible-root .collapsible-header {
  display: flex;
}
.collapsible-root .collapsible-header:has([data-state='open']) {
  justify-content: space-between;
  align-items: center;
}
```

2024-01-05 07:40 UTC, ivy-lli commented
Cool 👍

2024-01-05 08:23 UTC, merged